#!/bin/sh
set -e

#DEBHELPER#

case $1 in
	purge)
		rm -f /etc/reqstat/reqstat.yaml
		rmdir --ignore-fail-on-non-empty /etc/reqstat

		if which deluser >/dev/null 2>&1; then
			deluser --quiet reqstat > /dev/null || true
		fi
		;;
esac

exit 0
