---
  global:
    metrics:
      port: 9071
  input:
    type: syslog
    listen:
      ip: 127.0.0.1
      port: 2671
    format: combined # or regex
  metrics:
    - name: reqstat_nginx_status
      help: Count requests by HTTP status code
      type: counter
      fields:
        - name: status
          transform: http-code