---
  global:
    socket: /var/run/reqstat/reqstat.sock
    worker:
      threads: 2
  input:
    type: syslog
    listen:
      ip: 127.0.0.1
      port: 2671
    format: combined # or regex, json
  metrics:
    - type: counter
      field: status
      transform: http-code
